### ISSUE TITLE
homebrew tap error

### ISSUE THREAD

**Issue by jsermersheim-hv** [warrensbox/homebrew-tap#8]
I think there is an errant space in the urls for the most recent commit leading to the following error on my system:

```
Error: invalid attribute for formula 'warrensbox/tap/tfswitch': url ("https://github.com/warrensbox/terraform-switcher/releases/download/1.0.0/terraform-switcher_ 1.0.0_Darwin_arm64.tar.gz")
```

**Comment by yermulnik** [comment]
This is being worked on at the moment in scope of https://github.com/warrensbox/terraform-switcher/issues/339
Thanks for reporting

**Comment by yermulnik** [comment]
This should be fixed now via https://github.com/warrensbox/terraform-switcher/releases/tag/1.0.1

**Comment by jsermersheim-hv** [comment]
updating via brew pulled in 1.0.2 and i no longer see this error.  thanks for the quick turnaround
